# Generated by Django 3.2.4 on 2021-06-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTra', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
