# Generated by Django 3.2.4 on 2021-06-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTra', '0005_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
