# Generated by Django 3.1.3 on 2021-06-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=500)),
                ('starting_date', models.IntegerField()),
                ('estimated_time', models.IntegerField()),
            ],
        ),
    ]
