# Generated by Django 3.2.4 on 2021-06-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('Created', 'Created'), ('Paused', 'Paused'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Created', max_length=11),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='starting_date',
            field=models.IntegerField(),
        ),
    ]
