# Generated by Django 3.2.4 on 2021-06-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTra', '0004_alter_task_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('Created', 'Created'), ('Paused', 'Paused'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=11),
        ),
    ]
