# Generated by Django 3.2.4 on 2021-06-28 01:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('timeTra', '0006_alter_task_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('tasks', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=140),
        ),
    ]
