# Generated by Django 3.2.4 on 2021-06-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTra', '0007_auto_20210628_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('Created', 'Created'), ('Paused', 'Paused'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Created', max_length=11),
        ),
    ]
