# Generated by Django 3.2.4 on 2021-06-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeTra', '0008_alter_task_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_spent',
        ),
    ]
